export const TODOS = {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    REMOVE_DONE: 'REMOVE_DONE',
    MARK_ALL_AS_DONE: 'MARK_ALL_AS_DONE',
    REMOVE_ALL_DONE: 'REMOVE_ALL_DONE'
};

export const TODOS_TO_SHOW = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_DONE: 'SHOW_DONE',
    SHOW_NOT_DONE: 'SHOW_NOT_DONE',
}
